---
version: 2.1

docker-auth: &docker-auth
  auth:
    username: $DOCKERHUB_USERNAME
    password: $DOCKERHUB_PASSWORD

jobs:
  build:
    docker:
      - image: cimg/go:1.14.7
        <<: *docker-auth
    steps:
      - checkout
      - run:
          name: Build
          command: |
            export GOOS=linux
            export GOARCH=amd64
            mkdir -p ${GOPATH}/src/github.com/${CIRCLE_PROJECT_USERNAME}/
            ln -s ~/project ${GOPATH}/src/github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
            go build -o /tmp/grafana-reporter -v github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/cmd/grafana-reporter
      - store_artifacts:
          path: /tmp/grafana-reporter
          destination: grafana-reporter

workflows:
  version: 2
  main:
    jobs:
      - build:
          context: org-global
      - approve_publish:
          type: approval
          requires:
            - build
          filters:
            branches:
              ignore:
                - master
