---
version: 2.1

docker-auth: &docker-auth
  auth:
    username: $DOCKERHUB_USERNAME
    password: $DOCKERHUB_PASSWORD

jobs:
  build:
    docker:
      - image: cimg/go:1.14.7
        <<: *docker-auth
    working_directory: ${GOPATH}/src/github.com/${CIRCLE_PROJECT_USERNAME}
    steps:
      - checkout
      - run:
          name: Build
          command: |
            export GOOS=linux
            export GOARCH=amd64
            go build -v github.com/connectedservices/reporter/cmd/grafana-reporter

workflows:
  version: 2
  main:
    jobs:
      - build:
          context: org-global
      - approve_publish:
          type: approval
          requires:
            - build
          filters:
            branches:
              ignore:
                - master
