---
version: 2.1

docker-auth: &docker-auth
  auth:
    username: $DOCKERHUB_USERNAME
    password: $DOCKERHUB_PASSWORD

jobs:
  build:
    docker:
      - image: cimg/go:1.19.11
        <<: *docker-auth
    steps:
      - checkout
      - run:
          name: Build
          command: |
            export GOOS=linux
            export GOARCH=amd64

            export BUILD_DIR="$(pwd)/cmd/grafana-reporter"

            if [[ "$CIRCLE_BRANCH" =~ "master" ]]; then
              MAJOR=$(grep generatedMajor ${BUILD_DIR}/version.go |awk -F'=' '{print $2}' |tr -d ' "')
              MINOR=$(grep generatedMinor ${BUILD_DIR}/version.go |awk -F'=' '{print $2}' |tr -d ' "')
              RELEASE=$(grep generatedRelease ${BUILD_DIR}/version.go |awk -F'=' '{print $2}' |tr -d ' "''"')
              VERSION="${MAJOR}.${MINOR}-${RELEASE}"
            else
              VERSION=${CIRCLE_SHA1::7}
            fi

            go build -ldflags "-X main.generatedGitHash=${CIRCLE_SHA1}" -o bin/${VERSION}/grafana-reporter ./cmd/grafana-reporter

      - store_artifacts:
          path: bin/

workflows:
  version: 2
  main:
    jobs:
      - build:
          context: org-global
